import SharpRadialClipping.Attainable
import SharpRadialClipping.RandomLaw
import Mathlib.Probability.Distributions.Bernoulli

open MeasureTheory
open ProbabilityTheory
open unitInterval

/-!
# The `p = 1` attainable bias--energy region

This file proves the exact `p = 1` attainable region for arbitrary admissible
Hilbert-valued laws: the closed unit triangle with its top vertex excluded.
It includes two-atom constructions for the strict interior and the sloping
boundary.
-/

noncomputable section

universe u v

variable {H : Type v} [NormedAddCommGroup H]
  [InnerProductSpace ℝ H] [CompleteSpace H]

omit [CompleteSpace H] in
lemma norm_residual_add_norm_radialClip
    {τ : ℝ} (hτ : 0 < τ) (x : H) :
    ‖x - radialClip τ x‖ + ‖radialClip τ x‖ = ‖x‖ := by
  rw [norm_sub_radialClip hτ, norm_radialClip hτ]
  by_cases h : ‖x‖ ≤ τ
  · rw [max_eq_right (sub_nonpos.mpr h), min_eq_left h]
    simp
  · have hτnorm : τ ≤ ‖x‖ := le_of_lt (lt_of_not_ge h)
    rw [max_eq_left (sub_nonneg.mpr hτnorm), min_eq_right hτnorm]
    ring

omit [CompleteSpace H] in
/-- At `p = 1`, the pointwise clipping residual and clipped energy, with unit
weights, are bounded by the input norm. -/
theorem radialClip_residual_add_energy_le_norm
    {τ : ℝ} (hτ : 0 < τ) (x : H) :
    ‖x - radialClip τ x‖ + ‖radialClip τ x‖ ^ 2 / τ ≤ ‖x‖ := by
  rw [norm_sub_radialClip hτ, norm_radialClip hτ]
  by_cases h : ‖x‖ ≤ τ
  · rw [min_eq_left h, max_eq_right (sub_nonpos.mpr h)]
    have hn : 0 ≤ ‖x‖ := norm_nonneg x
    have hmul : ‖x‖ ^ 2 ≤ ‖x‖ * τ := by
      nlinarith [mul_nonneg hn (sub_nonneg.mpr h)]
    have hdiv : ‖x‖ ^ 2 / τ ≤ ‖x‖ :=
      (div_le_iff₀ hτ).2 hmul
    simpa using hdiv
  · have hτnorm : τ ≤ ‖x‖ := le_of_lt (lt_of_not_ge h)
    rw [min_eq_right hτnorm, max_eq_left (sub_nonneg.mpr hτnorm)]
    have hsq : τ ^ 2 / τ = τ := by
      rw [pow_two]
      field_simp
    rw [hsq]
    linarith

/-- The set of energy--bias pairs generated by all admissible `p = 1`
Hilbert-valued random vectors. -/
def attainableBiasEnergyPairsP1
    (H : Type v) [MeasurableSpace H] [NormedAddCommGroup H]
    [InnerProductSpace ℝ H] [CompleteSpace H] (τ : ℝ) : Set (ℝ × ℝ) :=
  Set.range fun law : RandomVectorLaw.{u, v} H 1 => law.biasEnergyPair τ

/-- A two-outcome law with one clipped atom and one zero atom. -/
def p1SingleAtom (a τ : ℝ) (e : H) : ULift.{u} Bool → H :=
  fun b => if b.down then (a * τ) • e else 0

lemma p1SingleAtom_norm_true {a τ : ℝ} (ha : 0 ≤ a) (hτ : 0 ≤ τ)
    {e : H} (he : ‖e‖ = 1) :
    ‖p1SingleAtom a τ e (ULift.up true)‖ = a * τ := by
  simp [p1SingleAtom, norm_smul, Real.norm_eq_abs,
    abs_of_nonneg ha, abs_of_nonneg hτ, he]

omit [CompleteSpace H] in
lemma p1SingleAtom_norm_false (a τ : ℝ) (e : H) :
    ‖p1SingleAtom a τ e (ULift.up false)‖ = 0 := by
  simp [p1SingleAtom]

lemma p1SingleAtom_clip_true {a τ : ℝ} (ha : 1 ≤ a) (hτ : 0 < τ)
    {e : H} (he : ‖e‖ = 1) :
    radialClip τ (p1SingleAtom a τ e (ULift.up true)) = τ • e := by
  have ha0 : 0 ≤ a := le_trans (by norm_num) ha
  have hnorm : ‖p1SingleAtom a τ e (ULift.up true)‖ = a * τ :=
    p1SingleAtom_norm_true ha0 hτ.le he
  rw [radialClip_eq_div_max_smul _ _ hτ, hnorm]
  have hmax : max (a * τ) τ = a * τ := max_eq_left (by nlinarith)
  rw [hmax]
  have hq : τ / (a * τ) * (a * τ) = τ := by
    field_simp [mul_ne_zero (by linarith : a ≠ 0) hτ.ne']
  simp only [p1SingleAtom, ↓reduceIte, smul_smul]
  rw [hq]

lemma p1SingleAtom_clip_false {τ : ℝ} (hτ : 0 ≤ τ) (a : ℝ) (e : H) :
    radialClip τ (p1SingleAtom a τ e (ULift.up false)) = 0 := by
  have hnorm : ‖p1SingleAtom a τ e (ULift.up false)‖ = 0 := by
    simp [p1SingleAtom]
  rw [radialClip_of_norm_le (by rw [hnorm]; exact hτ)]
  simp [p1SingleAtom]

lemma p1SingleAtom_mean
    {a τ q : ℝ} (ha : 1 ≤ a) (hτ : 0 < τ) (hq : 0 ≤ q) (hq1 : q ≤ 1)
    {e : H} (he : ‖e‖ = 1) :
    (∫ b, p1SingleAtom a τ e b ∂
        bernoulliMeasure (ULift.up true) (ULift.up false)
          (⟨q, hq, hq1⟩ : I)) = (q * a * τ) • e := by
  rw [integral_bernoulliMeasure]
  simp [p1SingleAtom, smul_smul]
  congr 1 <;> ring

lemma p1SingleAtom_clipped_mean
    {a τ q : ℝ} (ha : 1 ≤ a) (hτ : 0 < τ) (hq : 0 ≤ q) (hq1 : q ≤ 1)
    {e : H} (he : ‖e‖ = 1) :
    (∫ b, radialClip τ (p1SingleAtom a τ e b) ∂
        bernoulliMeasure (ULift.up true) (ULift.up false)
          (⟨q, hq, hq1⟩ : I)) = (q * τ) • e := by
  rw [integral_bernoulliMeasure, p1SingleAtom_clip_true ha hτ he,
    p1SingleAtom_clip_false hτ.le a e]
  simp [smul_smul, mul_assoc]

lemma p1SingleAtom_moment
    {a τ q : ℝ} (ha : 1 ≤ a) (hτ : 0 < τ) (hq : 0 ≤ q) (hq1 : q ≤ 1)
    {e : H} (he : ‖e‖ = 1) :
    (∫ b, ‖p1SingleAtom a τ e b‖ ^ (1 : ℝ) ∂
        bernoulliMeasure (ULift.up true) (ULift.up false)
          (⟨q, hq, hq1⟩ : I)) = q * a * τ := by
  rw [integral_bernoulliMeasure,
    p1SingleAtom_norm_true (by linarith) hτ.le he,
    p1SingleAtom_norm_false]
  simp only [Real.rpow_one, smul_eq_mul, mul_zero, zero_add]
  ring

lemma p1SingleAtom_centered_sq
    {a τ q : ℝ} (ha : 1 ≤ a) (hτ : 0 < τ) (hq : 0 ≤ q) (hq1 : q ≤ 1)
    {e : H} (he : ‖e‖ = 1) :
    (∫ b, ‖radialClip τ (p1SingleAtom a τ e b) -
        ∫ z, radialClip τ (p1SingleAtom a τ e z) ∂
          bernoulliMeasure (ULift.up true) (ULift.up false)
            (⟨q, hq, hq1⟩ : I)‖ ^ 2 ∂
        bernoulliMeasure (ULift.up true) (ULift.up false)
          (⟨q, hq, hq1⟩ : I)) = q * (1 - q) * τ ^ 2 := by
  rw [p1SingleAtom_clipped_mean ha hτ hq hq1 he,
    integral_bernoulliMeasure,
    p1SingleAtom_clip_true ha hτ he,
    p1SingleAtom_clip_false hτ.le a e]
  have htrue : τ • e - (q * τ) • e = ((1 - q) * τ) • e := by
    rw [← sub_smul]
    congr 1
    ring
  rw [htrue]
  simp only [norm_smul, Real.norm_eq_abs, he, mul_one,
    abs_of_nonneg (mul_nonneg (sub_nonneg.mpr hq1) hτ.le)]
  have hfalse : ‖-((q * τ) • e)‖ = q * τ := by
    rw [norm_neg, norm_smul, Real.norm_eq_abs, he, mul_one,
      abs_of_nonneg (mul_nonneg hq hτ.le)]
  have hfalse' : ‖0 - (q * τ) • e‖ = q * τ := by
    rw [show 0 - (q * τ) • e = -((q * τ) • e) by abel, hfalse]
  rw [hfalse']
  simp only [smul_eq_mul]
  ring

/- The boundary of the p=1 triangle, except for (0,1), is realized by a
   symmetric clipped law: one atom is at -τ and the other beyond +τ. -/
def p1BoundaryAtom (a τ : ℝ) (e : H) : ULift.{u} Bool → H :=
  fun b => if b.down then (a * τ) • e else (-τ) • e

lemma p1BoundaryAtom_norm_true {a τ : ℝ} (ha : 0 ≤ a) (hτ : 0 ≤ τ)
    {e : H} (he : ‖e‖ = 1) :
    ‖p1BoundaryAtom a τ e (ULift.up true)‖ = a * τ := by
  simp [p1BoundaryAtom, norm_smul, Real.norm_eq_abs,
    abs_of_nonneg ha, abs_of_nonneg hτ, he]

lemma p1BoundaryAtom_norm_false {a τ : ℝ} (ha : 0 ≤ a) (hτ : 0 ≤ τ)
    {e : H} (he : ‖e‖ = 1) :
    ‖p1BoundaryAtom a τ e (ULift.up false)‖ = τ := by
  simp [p1BoundaryAtom, norm_smul, Real.norm_eq_abs,
    abs_of_nonneg hτ, he]

lemma p1BoundaryAtom_clip_true {a τ : ℝ} (ha : 1 ≤ a) (hτ : 0 < τ)
    {e : H} (he : ‖e‖ = 1) :
    radialClip τ (p1BoundaryAtom a τ e (ULift.up true)) = τ • e := by
  have hnorm : ‖p1BoundaryAtom a τ e (ULift.up true)‖ = a * τ :=
    p1BoundaryAtom_norm_true (by linarith) hτ.le he
  rw [radialClip_eq_div_max_smul _ _ hτ, hnorm]
  have hmax : max (a * τ) τ = a * τ := max_eq_left (by nlinarith)
  rw [hmax]
  have hq : τ / (a * τ) * (a * τ) = τ := by
    field_simp [mul_ne_zero (by linarith : a ≠ 0) hτ.ne']
  simp only [p1BoundaryAtom, ↓reduceIte, smul_smul]
  rw [hq]

lemma p1BoundaryAtom_clip_false {a τ : ℝ} (ha : 1 ≤ a) (hτ : 0 < τ)
    {e : H} (he : ‖e‖ = 1) :
    radialClip τ (p1BoundaryAtom a τ e (ULift.up false)) = (-τ) • e := by
  have hnorm : ‖p1BoundaryAtom a τ e (ULift.up false)‖ = τ :=
    p1BoundaryAtom_norm_false (by linarith) hτ.le he
  rw [radialClip_of_norm_le (le_of_eq hnorm)]
  simp [p1BoundaryAtom]

lemma p1BoundaryAtom_mean {a τ : ℝ} (ha : 0 ≤ a) (hτ : 0 ≤ τ)
    {e : H} (he : ‖e‖ = 1) :
    (∫ b, p1BoundaryAtom a τ e b ∂
      bernoulliMeasure (ULift.up true) (ULift.up false) halfUnit) =
        (((a - 1) / 2) * τ) • e := by
  rw [integral_bernoulliMeasure]
  simp [p1BoundaryAtom, halfUnit, smul_smul]
  module

lemma p1BoundaryAtom_clipped_mean {a τ : ℝ} (ha : 1 ≤ a) (hτ : 0 < τ)
    {e : H} (he : ‖e‖ = 1) :
    (∫ b, radialClip τ (p1BoundaryAtom a τ e b) ∂
      bernoulliMeasure (ULift.up true) (ULift.up false) halfUnit) = 0 := by
  rw [integral_bernoulliMeasure,
    p1BoundaryAtom_clip_true ha hτ he,
    p1BoundaryAtom_clip_false ha hτ he]
  simp [halfUnit]
  module

lemma p1BoundaryAtom_moment {a τ : ℝ} (ha : 0 ≤ a) (hτ : 0 ≤ τ)
    {e : H} (he : ‖e‖ = 1) :
    (∫ b, ‖p1BoundaryAtom a τ e b‖ ^ (1 : ℝ) ∂
      bernoulliMeasure (ULift.up true) (ULift.up false) halfUnit) =
        ((a + 1) / 2) * τ := by
  rw [integral_bernoulliMeasure,
    p1BoundaryAtom_norm_true ha hτ he,
    p1BoundaryAtom_norm_false ha hτ he]
  simp [halfUnit, Real.rpow_one]
  ring

lemma p1BoundaryAtom_centered_sq {a τ : ℝ} (ha : 1 ≤ a) (hτ : 0 < τ)
    {e : H} (he : ‖e‖ = 1) :
    (∫ b, ‖radialClip τ (p1BoundaryAtom a τ e b) -
      ∫ z, radialClip τ (p1BoundaryAtom a τ e z) ∂
        bernoulliMeasure (ULift.up true) (ULift.up false) halfUnit‖ ^ 2 ∂
      bernoulliMeasure (ULift.up true) (ULift.up false) halfUnit) = τ ^ 2 := by
  rw [p1BoundaryAtom_clipped_mean ha hτ he,
    integral_bernoulliMeasure,
    p1BoundaryAtom_clip_true ha hτ he,
    p1BoundaryAtom_clip_false ha hτ he]
  simp [norm_smul, Real.norm_eq_abs, he, abs_of_nonneg hτ.le, halfUnit]
  ring

/-- Bernoulli realization of the `p = 1` boundary parametrization.  The
probability of the nonzero atom is `q`, and its radius is `a τ`. -/
theorem p1_bernoulli_pair_mem
    [MeasurableSpace H] [Nontrivial H] {a τ q : ℝ}
    (ha : 1 ≤ a) (hτ : 0 < τ)
    (hq : 0 < q) (hq1 : q ≤ 1) :
    ((1 - q) / a, (a - 1) / a) ∈ attainableBiasEnergyPairsP1.{u, v} H τ := by
  obtain ⟨e, he⟩ := exists_norm_eq_one (E := H)
  let qI : I := ⟨q, hq.le, hq1⟩
  let μ : Measure (ULift.{u} Bool) :=
    bernoulliMeasure (ULift.up true) (ULift.up false) qI
  let X : ULift.{u} Bool → H := p1SingleAtom a τ e
  let law : RandomVectorLaw.{u, v} H 1 := {
    Ω := ULift.{u} Bool
    mΩ := inferInstance
    μ := μ
    probability := inferInstance
    X := X
    memLp := MemLp.of_discrete
    moment_pos := by
      have hm' := p1SingleAtom_moment ha hτ qI.property.1 qI.property.2 he
      change 0 < ∫ b, ‖p1SingleAtom a τ e b‖ ^ (1 : ℝ) ∂
        bernoulliMeasure (ULift.up true) (ULift.up false) qI
      rw [hm']
      positivity
  }
  have hmoment : 0 < ∫ b, ‖X b‖ ^ (1 : ℝ) ∂μ := law.moment_pos
  have hmoment_eq : (∫ b, ‖X b‖ ^ (1 : ℝ) ∂μ) = q * a * τ := by
    dsimp [μ, X, qI]
    exact p1SingleAtom_moment ha hτ hq.le hq1 he
  have hmean : (∫ b, X b ∂μ) = (q * a * τ) • e := by
    dsimp [μ, X, qI]
    exact p1SingleAtom_mean ha hτ hq.le hq1 he
  have hclipmean : (∫ b, radialClip τ (X b) ∂μ) = (q * τ) • e := by
    dsimp [μ, X, qI]
    exact p1SingleAtom_clipped_mean ha hτ hq.le hq1 he
  have hvar :
      (∫ b, ‖radialClip τ (X b) -
        ∫ z, radialClip τ (X z) ∂μ‖ ^ 2 ∂μ) = q * (1 - q) * τ ^ 2 := by
    dsimp [μ, X, qI]
    exact p1SingleAtom_centered_sq ha hτ hq.le hq1 he
  have hnormdiff : ‖(q * τ) • e - (q * a * τ) • e‖ = q * (a - 1) * τ := by
    have hvec : (q * τ) • e - (q * a * τ) • e = (q * (1 - a) * τ) • e := by
      rw [← sub_smul]
      congr 1
      ring
    have harg : q * (1 - a) * τ ≤ 0 := by
      calc
        q * (1 - a) * τ = (q * τ) * (1 - a) := by ring
        _ ≤ 0 := mul_nonpos_of_nonneg_of_nonpos
          (mul_nonneg hq.le hτ.le) (sub_nonpos.mpr ha)
    rw [hvec, norm_smul, he, Real.norm_eq_abs, abs_of_nonpos harg]
    ring_nf
  have hbias : stochasticClippingRatio μ 1 0 1 τ X = (a - 1) / a := by
    dsimp [stochasticClippingRatio]
    rw [hclipmean, hmean, hnormdiff, hmoment_eq]
    norm_num only [show (1 : ℝ) - 1 = 0 by norm_num]
    simp only [Real.rpow_zero, Real.rpow_one, one_mul, zero_mul, add_zero]
    have ha0 : 0 < a := by linarith
    field_simp [ne_of_gt hτ, ne_of_gt hq, ne_of_gt ha0] <;> ring
  have henergy : stochasticClippingRatio μ 0 1 1 τ X = (1 - q) / a := by
    dsimp [stochasticClippingRatio]
    rw [hvar, hmoment_eq]
    norm_num only [show (1 : ℝ) - 1 = 0 by norm_num]
    simp only [Real.rpow_zero, Real.rpow_one, one_mul, zero_mul, zero_add]
    have ha0 : 0 < a := by linarith
    field_simp [ne_of_gt hτ, ne_of_gt hq, ne_of_gt ha0] <;> ring
  apply Set.mem_range.mpr
  refine ⟨law, ?_⟩
  exact Prod.ext henergy hbias

/-- Every strict interior point of the `p = 1` triangle is attained by a
two-atom law (in every sample-space universe). -/
theorem p1_strict_interior_mem_attainable
    [MeasurableSpace H] [Nontrivial H] {τ v₀ d₀ : ℝ}
    (hτ : 0 < τ) (hv : 0 ≤ v₀) (hd : 0 ≤ d₀)
    (hvd : v₀ + d₀ < 1) :
    (v₀, d₀) ∈ attainableBiasEnergyPairsP1.{u, v} H τ := by
  have hdlt : d₀ < 1 := by linarith
  have hden : 0 < 1 - d₀ := by linarith
  let a : ℝ := 1 / (1 - d₀)
  let q : ℝ := 1 - v₀ / (1 - d₀)
  have ha : 1 ≤ a := by
    dsimp [a]
    have hdenle : 1 - d₀ ≤ 1 := by linarith
    simpa [one_div] using (one_le_inv₀ hden).2 hdenle
  have hq : 0 < q := by
    dsimp [q]
    rw [show 1 - v₀ / (1 - d₀) = (1 - d₀ - v₀) / (1 - d₀) by
      field_simp]
    exact div_pos (by linarith) hden
  have hq1 : q ≤ 1 := by
    dsimp [q]
    have : 0 ≤ v₀ / (1 - d₀) := div_nonneg hv hden.le
    linarith
  have hvpair : (1 - q) / a = v₀ := by
    dsimp [a, q]
    field_simp [ne_of_gt hden]
    ring
  have hdpair : (a - 1) / a = d₀ := by
    dsimp [a]
    field_simp [ne_of_gt hden]
    ring
  have hwitness := p1_bernoulli_pair_mem.{u, v} (H := H) ha hτ hq hq1
  have hwitness' : ((1 - q) / a, (a - 1) / a) ∈
      attainableBiasEnergyPairsP1.{u, v} H τ := hwitness
  rw [hvpair, hdpair] at hwitness'
  exact hwitness'

/-- Every point on the sloping edge of the `p = 1` triangle, other than its
top vertex, is attained by a symmetric two-atom law. -/
theorem p1_boundary_mem_attainable
    [MeasurableSpace H] [Nontrivial H] {τ d₀ : ℝ}
    (hτ : 0 < τ) (hd : 0 ≤ d₀) (hdlt : d₀ < 1) :
    (1 - d₀, d₀) ∈ attainableBiasEnergyPairsP1.{u, v} H τ := by
  obtain ⟨e, he⟩ := exists_norm_eq_one (E := H)
  have hden : 0 < 1 - d₀ := by linarith
  let a : ℝ := (1 + d₀) / (1 - d₀)
  have ha : 1 ≤ a := by
    dsimp [a]
    apply (le_div_iff₀ hden).2
    nlinarith
  have hplus : a + 1 = 2 / (1 - d₀) := by
    dsimp [a]
    field_simp [ne_of_gt hden]
    ring
  have hminus : a - 1 = 2 * d₀ / (1 - d₀) := by
    dsimp [a]
    field_simp [ne_of_gt hden]
    ring
  let μ : Measure (ULift.{u} Bool) :=
    bernoulliMeasure (ULift.up true) (ULift.up false) halfUnit
  let X : ULift.{u} Bool → H := p1BoundaryAtom a τ e
  let law : RandomVectorLaw.{u, v} H 1 := {
    Ω := ULift.{u} Bool
    mΩ := inferInstance
    μ := μ
    probability := inferInstance
    X := X
    memLp := MemLp.of_discrete
    moment_pos := by
      have hm := p1BoundaryAtom_moment (a := a) (τ := τ)
        (le_trans (by norm_num : (0 : ℝ) ≤ 1) ha) hτ.le he
      change 0 < ∫ b, ‖p1BoundaryAtom a τ e b‖ ^ (1 : ℝ) ∂μ
      rw [show μ = bernoulliMeasure (ULift.up true) (ULift.up false) halfUnit by
        rfl, hm]
      positivity
  }
  have hmoment : 0 < ∫ b, ‖X b‖ ^ (1 : ℝ) ∂μ := law.moment_pos
  have hmoment_eq :
      (∫ b, ‖X b‖ ^ (1 : ℝ) ∂μ) = ((a + 1) / 2) * τ := by
    dsimp [μ, X]
    exact p1BoundaryAtom_moment (a := a) (τ := τ)
      (le_trans (by norm_num : (0 : ℝ) ≤ 1) ha) hτ.le he
  have hmean : (∫ b, X b ∂μ) = (((a - 1) / 2) * τ) • e := by
    dsimp [μ, X]
    exact p1BoundaryAtom_mean (a := a) (τ := τ)
      (le_trans (by norm_num : (0 : ℝ) ≤ 1) ha) hτ.le he
  have hclipmean : (∫ b, radialClip τ (X b) ∂μ) = 0 := by
    dsimp [μ, X]
    exact p1BoundaryAtom_clipped_mean ha hτ he
  have hvar :
      (∫ b, ‖radialClip τ (X b) -
        ∫ z, radialClip τ (X z) ∂μ‖ ^ 2 ∂μ) = τ ^ 2 := by
    dsimp [μ, X]
    exact p1BoundaryAtom_centered_sq ha hτ he
  have hnormmean :
      ‖(((a - 1) / 2) * τ) • e‖ = (((a - 1) / 2) * τ) := by
    have hcoeff : 0 ≤ ((a - 1) / 2) * τ := by positivity
    rw [norm_smul, Real.norm_eq_abs, he, abs_of_nonneg hcoeff]
    simp
  have hnormdiff :
      ‖(0 : H) - (((a - 1) / 2) * τ) • e‖ = ((a - 1) / 2) * τ := by
    rw [zero_sub, norm_neg, hnormmean]
  have hbias : stochasticClippingRatio μ 1 0 1 τ X = d₀ := by
    dsimp [stochasticClippingRatio]
    rw [hclipmean, hmean, hnormdiff, hmoment_eq]
    norm_num
    rw [hminus, hplus]
    field_simp [ne_of_gt hτ, ne_of_gt hden]
  have henergy : stochasticClippingRatio μ 0 1 1 τ X = 1 - d₀ := by
    dsimp [stochasticClippingRatio]
    rw [hvar, hmoment_eq]
    simp only [Real.rpow_zero, Real.rpow_one, one_mul, zero_mul, zero_add]
    norm_num
    rw [hplus]
    field_simp [ne_of_gt hτ, ne_of_gt hden]
  apply Set.mem_range.mpr
  refine ⟨law, ?_⟩
  exact Prod.ext henergy hbias

/-- The closed triangle appearing in the `p = 1` classification. -/
def p1ClosedTriangle : Set (ℝ × ℝ) :=
  {z | 0 ≤ z.1 ∧ 0 ≤ z.2 ∧ z.1 + z.2 ≤ 1}

/-- The normalized `p = 1` bias plus energy of any integrable Hilbert-valued
law lies in the closed unit triangle.  The assumption on the squared clipped
norm is automatic for probability measures, but is kept explicit here. -/
theorem stochastic_radialClip_p1_triangle
    {Ω : Type*} [MeasurableSpace Ω]
    (μ : Measure Ω) [IsProbabilityMeasure μ] (τ : ℝ) (hτ : 0 < τ)
    (X : Ω → H) (hX : Integrable X μ)
    (hY : Integrable (fun ω => radialClip τ (X ω)) μ)
    (hYsq : Integrable (fun ω => ‖radialClip τ (X ω)‖ ^ 2) μ)
    (hm : 0 < ∫ ω, ‖X ω‖ ∂μ) :
    (‖(∫ ω, radialClip τ (X ω) ∂μ) - ∫ ω, X ω ∂μ‖ +
        (1 / τ) *
          ∫ ω, ‖radialClip τ (X ω) - ∫ z, radialClip τ (X z) ∂μ‖ ^ 2 ∂μ) /
      (∫ ω, ‖X ω‖ ∂μ) ≤ 1 := by
  let Y : Ω → H := fun ω => radialClip τ (X ω)
  let b : H := ∫ ω, Y ω ∂μ
  let m : H := ∫ ω, X ω ∂μ
  have hres : Integrable (fun ω => ‖X ω - Y ω‖) μ := (hX.sub hY).norm
  have hnormX : Integrable (fun ω => ‖X ω‖) μ := hX.norm
  have hpoint : ∀ ω,
      ‖X ω - Y ω‖ + ‖Y ω‖ ^ 2 / τ ≤ ‖X ω‖ := by
    intro ω
    exact radialClip_residual_add_energy_le_norm hτ (X ω)
  have hsum : Integrable (fun ω =>
      ‖X ω - Y ω‖ + ‖Y ω‖ ^ 2 / τ) μ := by
    have henergy : Integrable (fun ω => ‖Y ω‖ ^ 2 / τ) μ := by
      simpa [Y, div_eq_mul_inv, mul_comm] using hYsq.const_mul τ⁻¹
    exact hres.add henergy
  have hint := integral_mono hsum hnormX (fun ω => hpoint ω)
  have hsum_le : (∫ ω, ‖X ω - Y ω‖ + ‖Y ω‖ ^ 2 / τ ∂μ)
      ≤ ∫ ω, ‖X ω‖ ∂μ := hint
  have hbias : ‖b - m‖ ≤ ∫ ω, ‖X ω - Y ω‖ ∂μ := by
    calc
      ‖b - m‖ = ‖∫ ω, Y ω - X ω ∂μ‖ := by
        rw [integral_sub hY hX]
      _ ≤ ∫ ω, ‖Y ω - X ω‖ ∂μ := norm_integral_le_integral_norm _
      _ = ∫ ω, ‖X ω - Y ω‖ ∂μ := by
        apply integral_congr_ae
        exact Filter.Eventually.of_forall fun ω => norm_sub_rev _ _
  have hvar :
      (∫ ω, ‖Y ω - b‖ ^ 2 ∂μ) =
        (∫ ω, ‖Y ω‖ ^ 2 ∂μ) - ‖b‖ ^ 2 := by
    exact integral_norm_sub_mean_sq μ Y hY hYsq
  have hvarle :
      (∫ ω, ‖Y ω - b‖ ^ 2 ∂μ) ≤ ∫ ω, ‖Y ω‖ ^ 2 ∂μ := by
    rw [hvar]
    nlinarith [sq_nonneg ‖b‖]
  have hτinv : 0 ≤ 1 / τ := by positivity
  have hcombined :
      ‖b - m‖ + (1 / τ) * (∫ ω, ‖Y ω - b‖ ^ 2 ∂μ)
        ≤ ∫ ω, ‖X ω‖ ∂μ := by
    have hint_expand :
        (∫ ω, ‖X ω - Y ω‖ + ‖Y ω‖ ^ 2 / τ ∂μ) =
          (∫ ω, ‖X ω - Y ω‖ ∂μ) +
            (1 / τ) * (∫ ω, ‖Y ω‖ ^ 2 ∂μ) := by
      calc
        (∫ ω, ‖X ω - Y ω‖ + ‖Y ω‖ ^ 2 / τ ∂μ)
            = (∫ ω, ‖X ω - Y ω‖ ∂μ) +
                ∫ ω, ‖Y ω‖ ^ 2 / τ ∂μ := by
                  rw [integral_add hres (by
                    simpa [div_eq_mul_inv, mul_comm, Y] using
                      hYsq.const_mul τ⁻¹)]
        _ = (∫ ω, ‖X ω - Y ω‖ ∂μ) +
              (1 / τ) * (∫ ω, ‖Y ω‖ ^ 2 ∂μ) := by
                rw [show (fun ω => ‖Y ω‖ ^ 2 / τ) =
                  (fun ω => τ⁻¹ * ‖Y ω‖ ^ 2) by
                    funext ω
                    simp [div_eq_mul_inv, mul_comm], integral_const_mul]
                simp [one_div]
    calc
      ‖b - m‖ + (1 / τ) * (∫ ω, ‖Y ω - b‖ ^ 2 ∂μ)
          ≤ (∫ ω, ‖X ω - Y ω‖ ∂μ) +
              (1 / τ) * (∫ ω, ‖Y ω‖ ^ 2 ∂μ) := by
            exact add_le_add hbias
              (mul_le_mul_of_nonneg_left hvarle hτinv)
      _ = ∫ ω, ‖X ω - Y ω‖ + ‖Y ω‖ ^ 2 / τ ∂μ := hint_expand.symm
      _ ≤ ∫ ω, ‖X ω‖ ∂μ := hsum_le
  have hratio :
      (‖b - m‖ + (1 / τ) *
        (∫ ω, ‖Y ω - b‖ ^ 2 ∂μ)) /
        (∫ ω, ‖X ω‖ ∂μ) ≤ 1 := by
    exact (div_le_iff₀ hm).2 (by simpa using hcombined)
  simpa [Y, b, m] using hratio

omit [CompleteSpace H] in
/-- A nonzero first moment forces the expected clipped norm to be positive. -/
theorem integral_norm_radialClip_pos_of_integral_norm_pos
    {Ω : Type*} [MeasurableSpace Ω]
    (μ : Measure Ω) {τ : ℝ} (hτ : 0 < τ) (X : Ω → H)
    (hX : Integrable X μ)
    (hXnorm : 0 < ∫ ω, ‖X ω‖ ∂μ)
    (hY : Integrable (fun ω => radialClip τ (X ω)) μ) :
    0 < ∫ ω, ‖radialClip τ (X ω)‖ ∂μ := by
  have hnormX : Integrable (fun ω => ‖X ω‖) μ := hX.norm
  have hsupport : 0 < μ (Function.support fun ω => ‖X ω‖) :=
    (integral_pos_iff_support_of_nonneg (fun _ => norm_nonneg _)
      hnormX).mp hXnorm
  have hsubset : Function.support (fun ω => ‖X ω‖) ⊆
      Function.support (fun ω => ‖radialClip τ (X ω)‖) := by
    intro ω hω
    have hx : X ω ≠ 0 := by
      intro hz
      apply hω
      simp [hz]
    have hxpos : 0 < ‖X ω‖ := norm_pos_iff.mpr hx
    have hclippos : 0 < ‖radialClip τ (X ω)‖ := by
      rw [norm_radialClip hτ]
      exact lt_min hxpos hτ
    exact hclippos.ne'
  have hclipSupport :
      0 < μ (Function.support fun ω => ‖radialClip τ (X ω)‖) :=
    lt_of_lt_of_le hsupport (measure_mono hsubset)
  exact (integral_pos_iff_support_of_nonneg
      (fun _ => norm_nonneg _) hY.norm).mpr hclipSupport

omit [CompleteSpace H] in
/-- The normalized clipping bias at `p = 1` is strictly less than one for
every admissible law with positive first moment.  In particular, the vertex
`(0,1)` of the closed triangle cannot be attained. -/
theorem stochasticClippingBiasRatio_p1_lt_one
    {Ω : Type*} [MeasurableSpace Ω]
    (μ : Measure Ω) [IsProbabilityMeasure μ] (τ : ℝ) (hτ : 0 < τ)
    (X : Ω → H) (hX : Integrable X μ)
    (hY : Integrable (fun ω => radialClip τ (X ω)) μ)
    (hm : 0 < ∫ ω, ‖X ω‖ ∂μ) :
    stochasticClippingRatio μ 1 0 1 τ X < 1 := by
  let Y : Ω → H := fun ω => radialClip τ (X ω)
  let b : H := ∫ ω, Y ω ∂μ
  let m : H := ∫ ω, X ω ∂μ
  have hres : Integrable (fun ω => ‖X ω - Y ω‖) μ := (hX.sub hY).norm
  have hclipnorm : Integrable (fun ω => ‖Y ω‖) μ := hY.norm
  have hclippos : 0 < ∫ ω, ‖Y ω‖ ∂μ :=
    integral_norm_radialClip_pos_of_integral_norm_pos μ hτ X hX hm hY
  have hsum_eq :
      (∫ ω, ‖X ω - Y ω‖ ∂μ) + (∫ ω, ‖Y ω‖ ∂μ) =
        ∫ ω, ‖X ω‖ ∂μ := by
    rw [← integral_add hres hclipnorm]
    apply integral_congr_ae
    exact Filter.Eventually.of_forall fun ω =>
      norm_residual_add_norm_radialClip hτ (X ω)
  have hbias : ‖b - m‖ ≤ ∫ ω, ‖X ω - Y ω‖ ∂μ := by
    calc
      ‖b - m‖ = ‖∫ ω, Y ω - X ω ∂μ‖ := by rw [integral_sub hY hX]
      _ ≤ ∫ ω, ‖Y ω - X ω‖ ∂μ := norm_integral_le_integral_norm _
      _ = ∫ ω, ‖X ω - Y ω‖ ∂μ := by
        apply integral_congr_ae
        exact Filter.Eventually.of_forall fun ω => norm_sub_rev _ _
  have hbiaslt : ‖b - m‖ < ∫ ω, ‖X ω‖ ∂μ := by
    rw [← hsum_eq]
    linarith
  have hden : 0 < τ ^ (1 - (1 : ℝ)) * (∫ ω, ‖X ω‖ ^ (1 : ℝ) ∂μ) := by
    simpa using mul_pos (Real.rpow_pos_of_pos hτ 0) hm
  dsimp [stochasticClippingRatio]
  simpa [Y, b, m, Real.rpow_zero, Real.rpow_one] using
    (div_lt_one hden).2 (by simpa using hbiaslt)

/-- Every admissible `p = 1` pair lies in the closed triangle from
Remark 4.2, with the top vertex excluded. -/
theorem attainableBiasEnergyPairsP1_subset_triangle
    (H : Type v) [MeasurableSpace H] [NormedAddCommGroup H]
    [InnerProductSpace ℝ H] [CompleteSpace H] {τ : ℝ} (hτ : 0 < τ) :
    attainableBiasEnergyPairsP1.{u, v} H τ ⊆
      {z : ℝ × ℝ | 0 ≤ z.1 ∧ 0 ≤ z.2 ∧ z.1 + z.2 ≤ 1 ∧ z.2 < 1} := by
  intro z hz
  rcases hz with ⟨law, rfl⟩
  letI : MeasurableSpace law.Ω := law.mΩ
  letI : IsProbabilityMeasure law.μ := law.probability
  have hX : Integrable law.X law.μ :=
    law.memLp.integrable (ENNReal.one_le_ofReal.mpr (by norm_num))
  have hY : Integrable (fun ω => radialClip τ (law.X ω)) law.μ :=
    integrable_radialClip law.memLp.1 hτ
  have hYsq : Integrable
      (fun ω => ‖radialClip τ (law.X ω)‖ ^ 2) law.μ :=
    integrable_sq_norm_radialClip law.memLp.1 hτ
  have hm : 0 < ∫ ω, ‖law.X ω‖ ∂law.μ := by
    simpa only [Real.rpow_one] using law.moment_pos
  have htriangle := stochastic_radialClip_p1_triangle law.μ τ hτ
    law.X hX hY hYsq hm
  have hbiaslt := stochasticClippingBiasRatio_p1_lt_one law.μ τ hτ
    law.X hX hY hm
  constructor
  · dsimp [RandomVectorLaw.biasEnergyPair, stochasticClippingRatio]
    positivity
  constructor
  · dsimp [RandomVectorLaw.biasEnergyPair, stochasticClippingRatio]
    positivity
  constructor
  · have hcoord :
        (stochasticClippingRatio law.μ 0 1 1 τ law.X) +
          (stochasticClippingRatio law.μ 1 0 1 τ law.X) ≤ 1 := by
      have hcoord_eq :
          stochasticClippingRatio law.μ 0 1 1 τ law.X +
              stochasticClippingRatio law.μ 1 0 1 τ law.X =
            (‖(∫ ω, radialClip τ (law.X ω) ∂law.μ) -
                ∫ ω, law.X ω ∂law.μ‖ +
              (1 / τ) *
                ∫ ω, ‖radialClip τ (law.X ω) -
                    ∫ z, radialClip τ (law.X z) ∂law.μ‖ ^ 2 ∂law.μ) /
              (∫ ω, ‖law.X ω‖ ∂law.μ) := by
        dsimp [stochasticClippingRatio]
        simp only [show (1 : ℝ) - 1 = 0 by norm_num,
          Real.rpow_zero, Real.rpow_one, one_mul, zero_mul, zero_div,
          add_zero]
        field_simp [ne_of_gt hm]
        ring
      rw [hcoord_eq]
      exact htriangle
    exact hcoord
  · exact hbiaslt

/-- Exact `p = 1` classification: every point in the closed unit triangle is
attainable except the top vertex `(0,1)`. -/
theorem attainableBiasEnergyPairsP1_eq_triangle_diff_top
    (H : Type v) [MeasurableSpace H] [NormedAddCommGroup H]
    [InnerProductSpace ℝ H] [CompleteSpace H] [Nontrivial H]
    {τ : ℝ} (hτ : 0 < τ) :
    attainableBiasEnergyPairsP1.{u, v} H τ = p1ClosedTriangle \ {(0, 1)} := by
  apply Set.ext
  intro z
  constructor
  · intro hz
    have hz' := attainableBiasEnergyPairsP1_subset_triangle H hτ hz
    refine ⟨?_, ?_⟩
    · exact ⟨hz'.1, hz'.2.1, hz'.2.2.1⟩
    · intro htop
      have : z.2 = 1 := by simpa using congrArg Prod.snd htop
      linarith [hz'.2.2.2]
  · rintro ⟨⟨hv, hd, hsum⟩, hnotTop⟩
    have hdle : z.2 ≤ 1 := by linarith
    have hdlt : z.2 < 1 := by
      apply lt_of_le_of_ne hdle
      intro hd_eq
      apply hnotTop
      apply Prod.ext
      · have hvzero : z.1 = 0 := by linarith
        exact hvzero
      · exact hd_eq
    by_cases hstrict : z.1 + z.2 < 1
    · exact p1_strict_interior_mem_attainable hτ hv hd hstrict
    · have heq : z.1 + z.2 = 1 := le_antisymm hsum (le_of_not_gt hstrict)
      have hfirst : z.1 = 1 - z.2 := by linarith
      rw [show z = (1 - z.2, z.2) by
        apply Prod.ext
        · exact hfirst
        · rfl]
      exact p1_boundary_mem_attainable hτ hd hdlt

/-- The vertex `(1,0)` of the `p = 1` region is attained by the symmetric
two-point law at the clipping radius. -/
theorem p1_endpoint_one_zero_mem_attainable
    [Nontrivial H] [MeasurableSpace H] {τ : ℝ} (hτ : 0 < τ) :
    (1, 0) ∈ attainableBiasEnergyPairsP1.{0, v} H τ := by
  obtain ⟨e, he⟩ := exists_norm_eq_one (E := H)
  let X : Bool → H := symmetricTwoPoint τ e
  let law : RandomVectorLaw H 1 := {
    Ω := Bool
    mΩ := inferInstance
    μ := symmetricBernoulli
    probability := inferInstance
    X := X
    memLp := MemLp.of_discrete
    moment_pos := by
      dsimp [X]
      rw [integral_norm_symmetricTwoPoint_rpow hτ he]
      exact Real.rpow_pos_of_pos hτ 1
  }
  apply Set.mem_range.mpr
  refine ⟨law, ?_⟩
  dsimp [RandomVectorLaw.biasEnergyPair, law, X]
  exact normalizedBiasEnergyPair_symmetric_eq hτ he
